import sqlite3
import os

# Path to the database
db_path = r"c:/Users/hobo/Desktop/Proxion/integrations/calibre-integration/config/app.db"
# The hash generated by Werkzeug
new_hash = "pbkdf2:sha256:260000$FXDaRbeDRRZA0t5B$9e6bf760b0261537f7cc8d31addff7825271d8cd9a455c73d066b80283f39a0c"

try:
    if not os.path.exists(db_path):
        print(f"Error: Database file not found at {db_path}")
        exit(1)

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Update the admin user (nickname='admin')
    cursor.execute("UPDATE user SET password = ? WHERE nickname = ?", (new_hash, "admin"))
    
    if cursor.rowcount == 0:
        print("Warning: No user found with nickname 'admin'. Checking 'name' column...")
        cursor.execute("UPDATE user SET password = ? WHERE name = ?", (new_hash, "admin"))
    
    if cursor.rowcount > 0:
        print(f"Success: Updated password for user 'admin'. Rows affected: {cursor.rowcount}")
        conn.commit()
    else:
        print("Error: Could not find 'admin' user to update.")
        
    conn.close()
except Exception as e:
    print(f"Exception: {e}")
